name: Sync Hourly

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
    inputs:
      recipe:
        description: Sync manually
        required: false

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Check For Changes
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Generate Stuff
        run: |
          npm install
          npm upgrade pogo-data-generator
          npm upgrade pogo-protos
          npm start
      - name: Configure git
        run: |
          git config --global user.name "turtlesocks-bot"
          git config --global user.email "turtlesocks-bot@users.noreply.github.com"
      - name: Generate Stuff
        run: |
          git add --all
          git commit --message "Hourly Sync"
          git push
